-- MySQL Script generated by MySQL Workbench
-- 02/08/16 10:17:12
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema spa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema spa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `spa` DEFAULT CHARACTER SET utf8 ;
USE `spa` ;

-- -----------------------------------------------------
-- Table `spa`.`paises`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spa`.`paises` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spa`.`idiomas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spa`.`idiomas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spa`.`hoteles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spa`.`hoteles` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `ubicacion` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spa`.`circustancias_medicas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spa`.`circustancias_medicas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spa`.`agencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spa`.`agencias` (
  `id` INT NOT NULL,
  `razon_social` VARCHAR(45) NULL,
  `nombre_comercial` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `correo_electronico` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spa`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spa`.`clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pais_id` INT NOT NULL,
  `idioma_id` INT NOT NULL,
  `hotel_id` INT NOT NULL,
  `agencia_id` INT NOT NULL,
  `circustancias_medica_id` INT NOT NULL,
  `fecha_alta` DATE NULL,
  `nombre` VARCHAR(60) NULL,
  `apellidos` VARCHAR(255) NULL,
  `edad` INT NULL,
  `correo_electronico` VARCHAR(255) NULL,
  `habitacion` VARCHAR(50) NULL,
  `firma` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `pais_id`, `idioma_id`, `hotel_id`, `agencia_id`, `circustancias_medica_id`),
  INDEX `fk_clientes_paises1_idx` (`pais_id` ASC),
  INDEX `fk_clientes_idiomas1_idx` (`idioma_id` ASC),
  INDEX `fk_clientes_hoteles1_idx` (`hotel_id` ASC),
  INDEX `fk_clientes_circustancias_medicas1_idx` (`circustancias_medica_id` ASC),
  INDEX `fk_clientes_agencias1_idx` (`agencia_id` ASC),
  CONSTRAINT `fk_clientes_paises1`
    FOREIGN KEY (`pais_id`)
    REFERENCES `spa`.`paises` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clientes_idiomas1`
    FOREIGN KEY (`idioma_id`)
    REFERENCES `spa`.`idiomas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clientes_hoteles1`
    FOREIGN KEY (`hotel_id`)
    REFERENCES `spa`.`hoteles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clientes_circustancias_medicas1`
    FOREIGN KEY (`circustancias_medica_id`)
    REFERENCES `spa`.`circustancias_medicas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clientes_agencias1`
    FOREIGN KEY (`agencia_id`)
    REFERENCES `spa`.`agencias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spa`.`terapeutas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spa`.`terapeutas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spa`.`opiniones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spa`.`opiniones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spa`.`tratamientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spa`.`tratamientos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spa`.`sesiones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spa`.`sesiones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `opinion_id` INT NOT NULL,
  `cliente_id` INT NOT NULL,
  `terapeuta_id` INT NOT NULL,
  `tratamiento_id` INT NOT NULL,
  PRIMARY KEY (`id`, `opinion_id`, `cliente_id`, `terapeuta_id`, `tratamiento_id`),
  INDEX `fk_sesiones_clientes_idx` (`cliente_id` ASC),
  INDEX `fk_sesiones_terapeutas1_idx` (`terapeuta_id` ASC),
  INDEX `fk_sesiones_tratamientos1_idx` (`tratamiento_id` ASC),
  INDEX `fk_sesiones_calificaciones1_idx` (`opinion_id` ASC),
  CONSTRAINT `fk_sesiones_clientes`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `spa`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sesiones_terapeutas1`
    FOREIGN KEY (`terapeuta_id`)
    REFERENCES `spa`.`terapeutas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sesiones_tratamientos1`
    FOREIGN KEY (`tratamiento_id`)
    REFERENCES `spa`.`tratamientos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sesiones_calificaciones1`
    FOREIGN KEY (`opinion_id`)
    REFERENCES `spa`.`opiniones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
